// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace PrintingServer.Domain.Entities;

public class ClientReport : BaseEntity
{
    public Guid ReportId { get; set; }

    public Guid ClientId { get; set; }

    public Guid PrinterId { get; set; }

    public string ReportName { get; set; }

    public string ClientName { get; set; }

    public string ClientIp { get; set; }

    public string PrinterName { get; set; }

    public string PrinterIp { get; set; }

    public virtual Client Client { get; set; }

    public virtual Printer Printer { get; set; }

    public virtual Report Report { get; set; }
    public virtual ICollection<Printed> Printeds { get; set; } = new List<Printed>();

    public ClientReport() { }
    public ClientReport(Guid userId, Guid reportId, Guid clientId, Guid printerId, string reportName, string clientName, string clientIp, string printerName, string printerIp)
    {
        AppUserId = userId;
        ReportId = reportId;
        ClientId = clientId;
        PrinterId = printerId;
        ReportName = reportName;
        ClientName = clientName;
        ClientIp = clientIp;
        PrinterName = printerName;
        PrinterIp = printerIp;
    }
    public void Update(Guid userId, Guid reportId, Guid clientId, Guid printerId, string reportName, string clientName, string clientIp, string printerName, string printerIp, bool isdeleted, bool isactive, string name = "", string description = "")
    {
        AppUserId = userId;
        ReportId = reportId;
        ClientId = clientId;
        PrinterId = printerId;
        ReportName = reportName;
        ClientName = clientName;
        ClientIp = clientIp;
        PrinterName = printerName;
        PrinterIp = printerIp;
        base.Update(isdeleted, isactive, name, description);
    }
    public void Update(Guid userId, Guid reportId, Guid clientId, Guid printerId, string reportName, string clientName, string clientIp, string printerName, string printerIp)
    {
        AppUserId = userId;
        ReportId = reportId;
        ClientId = clientId;
        PrinterId = printerId;
        ReportName = reportName;
        ClientName = clientName;
        ClientIp = clientIp;
        PrinterName = printerName;
        PrinterIp = printerIp;
        base.Update(this.IsDeleted, this.IsActive, this.Name, this.Description);
    }

    public override bool Equals(object obj)
    {
        return obj is ClientReport report &&
               ReportName == report.ReportName &&
               ClientName == report.ClientName &&
               ClientIp == report.ClientIp;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(ReportName, ClientName, ClientIp);
    }
    public override string ToString() => JsonSerializer.Serialize(this);
}