// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace PrintingServer.Domain.Entities;

public partial class Country : BaseEntity
{
    public string CountryCode { get; set; }

    public string CountryEnName { get; set; }

    public string CountryArName { get; set; }

    public string CountryEnNationality { get; set; }

    public string CountryArNationality { get; set; }
    public Country() { }
    public Country(Guid userId, string countryCode, string countryEnName, string countryArName, string countryEnNationality, string countryArNationality)
    {
        AppUserId = userId;
        CountryCode = countryCode;
        CountryEnName = countryEnName;
        CountryArName = countryArName;
        CountryEnNationality = countryEnNationality;
        CountryArNationality = countryArNationality;
    }
    public void Update(Guid userId, string countryCode, string countryEnName, string countryArName, string countryEnNationality, string countryArNationality)
    {
        AppUserId = userId;
        CountryCode = countryCode;
        CountryEnName = countryEnName;
        CountryArName = countryArName;
        CountryEnNationality = countryEnNationality;
        CountryArNationality = countryArNationality;
        base.Update(IsDeleted, IsActive, Name, Description);
    }
    public void Update(Guid userId, string countryCode, string countryEnName, string countryArName, string countryEnNationality, string countryArNationality, bool isdeleted, bool isactive, string name = "", string description = "")
    {
        AppUserId = userId;
        CountryCode = countryCode;
        CountryEnName = countryEnName;
        CountryArName = countryArName;
        CountryEnNationality = countryEnNationality;
        CountryArNationality = countryArNationality;
        base.Update(isdeleted, isactive, name, description);
    }
    public override string ToString() => JsonSerializer.Serialize(this);
}