// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace PrintingServer.Domain.Entities;

public partial class Printer : BaseEntity
{
    public string PrinterName { get; set; }

    public string PrinterIp { get; set; }

    public int ResponseTime { get; set; }

    public virtual ICollection<ClientReport> ClientReports { get; set; } = new List<ClientReport>();

    public virtual ICollection<PrinterErrorLog> PrinterErrorLogs { get; set; } = new List<PrinterErrorLog>();
    public Printer() { }
    public Printer(Guid userId, string printerName, string printerIp, int responseTime)
    {
        AppUserId = userId;
        PrinterName = printerName;
        PrinterIp = printerIp;
        ResponseTime = responseTime;
        IsActive = true;
    }
    public void Update(Guid userId, string printerName, string printerIp, int responseTime)
    {
        AppUserId = userId;
        PrinterName = printerName;
        PrinterIp = printerIp;
        ResponseTime = responseTime;
        base.Update(IsDeleted, IsActive, Name, Description);
    }
    public void Update(Guid userId, string printerName, string printerIp, int responseTime, bool isdeleted, bool isactive, string name = "", string description = "")
    {
        AppUserId = userId;
        PrinterName = printerName;
        PrinterIp = printerIp;
        ResponseTime = responseTime;
        base.Update(isdeleted, isactive, name, description);
    }

    public override bool Equals(object obj)
    {
        return obj is Printer printer &&
               PrinterName == printer.PrinterName &&
               PrinterIp == printer.PrinterIp &&
               ResponseTime == printer.ResponseTime;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(PrinterName, PrinterIp, ResponseTime);
    }
    public override string ToString() => JsonSerializer.Serialize(this);
}