// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace PrintingServer.Domain.Entities;

public partial class Printed : BaseEntity
{
    public Guid ClientReportId { get; set; }

    public DateTime PrintedTime { get; set; }

    public string MainObjectGuid { get; set; }

    public string PrintedBy { get; set; }

    public virtual ClientReport ClientReport { get; set; }
    public Printed() { }
    public Printed(Guid userId, Guid clientReportId, DateTime printedTime, string mainObjectGuid, string printedBy)
    {
        AppUserId = userId;
        ClientReportId = clientReportId;
        PrintedTime = printedTime;
        MainObjectGuid = mainObjectGuid;
        PrintedBy = printedBy;
    }
    public void Update(Guid userId, Guid clientReportId, DateTime printedTime, string mainObjectGuid, string printedBy)
    {
        AppUserId = userId;
        ClientReportId = clientReportId;
        PrintedTime = printedTime;
        MainObjectGuid = mainObjectGuid;
        PrintedBy = printedBy;
        base.Update(IsDeleted, IsActive, Name, Description);
    }
    public void Update(Guid userId, Guid clientReportId, DateTime printedTime, string mainObjectGuid, string printedBy, bool isdeleted, bool isactive, string name = "", string description = "")
    {
        AppUserId = userId;
        ClientReportId = clientReportId;
        PrintedTime = printedTime;
        MainObjectGuid = mainObjectGuid;
        PrintedBy = printedBy;
        base.Update(isdeleted, isactive, name, description);
    }
    public override string ToString() => JsonSerializer.Serialize(this);

}