// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace PrintingServer.Domain.Entities;

public partial class Report : BaseEntity
{
    public Guid PrinterId { get; set; }

    public string ReportName { get; set; }

    public string ReportPath { get; set; }

    public virtual ICollection<ClientReport> ClientReports { get; set; } = new List<ClientReport>();
    public Report() { }
    public Report(Guid userId, Guid printerId, string reportName, string reportPath)
    {
        AppUserId = userId;
        PrinterId = printerId;
        ReportName = reportName;
        ReportPath = reportPath;
        IsActive = true;
    }
    public void Update(Guid userId, Guid printerId, string reportName, string reportPath)
    {
        AppUserId = userId;
        PrinterId = printerId;
        ReportName = reportName;
        ReportPath = reportPath;
        base.Update(IsDeleted, IsActive, Name, Description);
    }
    public void Update(Guid userId, Guid printerId, string reportName, string reportPath, bool isdeleted, bool isactive, string name = "", string description = "")
    {
        AppUserId = userId;
        PrinterId = printerId;
        ReportName = reportName;
        ReportPath = reportPath;
        base.Update(isdeleted, isactive, name, description);
    }

    public override bool Equals(object obj)
    {
        return obj is Report report &&
               ReportName == report.ReportName &&
               ReportPath == report.ReportPath;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(ReportName, ReportPath);
    }
    public override string ToString() => JsonSerializer.Serialize(this);
}